/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MygroupsIndexImport } from './routes/mygroups.index'
import { Route as MygroupsGroupNameImport } from './routes/mygroups.$groupName'

// Create Virtual Routes

const HiscoreLazyImport = createFileRoute('/hiscore')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const HiscoreLazyRoute = HiscoreLazyImport.update({
  id: '/hiscore',
  path: '/hiscore',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/hiscore.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MygroupsIndexRoute = MygroupsIndexImport.update({
  id: '/mygroups/',
  path: '/mygroups/',
  getParentRoute: () => rootRoute,
} as any)

const MygroupsGroupNameRoute = MygroupsGroupNameImport.update({
  id: '/mygroups/$groupName',
  path: '/mygroups/$groupName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/hiscore': {
      id: '/hiscore'
      path: '/hiscore'
      fullPath: '/hiscore'
      preLoaderRoute: typeof HiscoreLazyImport
      parentRoute: typeof rootRoute
    }
    '/mygroups/$groupName': {
      id: '/mygroups/$groupName'
      path: '/mygroups/$groupName'
      fullPath: '/mygroups/$groupName'
      preLoaderRoute: typeof MygroupsGroupNameImport
      parentRoute: typeof rootRoute
    }
    '/mygroups/': {
      id: '/mygroups/'
      path: '/mygroups'
      fullPath: '/mygroups'
      preLoaderRoute: typeof MygroupsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/hiscore': typeof HiscoreLazyRoute
  '/mygroups/$groupName': typeof MygroupsGroupNameRoute
  '/mygroups': typeof MygroupsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/hiscore': typeof HiscoreLazyRoute
  '/mygroups/$groupName': typeof MygroupsGroupNameRoute
  '/mygroups': typeof MygroupsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/hiscore': typeof HiscoreLazyRoute
  '/mygroups/$groupName': typeof MygroupsGroupNameRoute
  '/mygroups/': typeof MygroupsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hiscore' | '/mygroups/$groupName' | '/mygroups'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hiscore' | '/mygroups/$groupName' | '/mygroups'
  id: '__root__' | '/' | '/hiscore' | '/mygroups/$groupName' | '/mygroups/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  HiscoreLazyRoute: typeof HiscoreLazyRoute
  MygroupsGroupNameRoute: typeof MygroupsGroupNameRoute
  MygroupsIndexRoute: typeof MygroupsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  HiscoreLazyRoute: HiscoreLazyRoute,
  MygroupsGroupNameRoute: MygroupsGroupNameRoute,
  MygroupsIndexRoute: MygroupsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hiscore",
        "/mygroups/$groupName",
        "/mygroups/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/hiscore": {
      "filePath": "hiscore.lazy.tsx"
    },
    "/mygroups/$groupName": {
      "filePath": "mygroups.$groupName.tsx"
    },
    "/mygroups/": {
      "filePath": "mygroups.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
