/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HiscoreLazyImport = createFileRoute('/hiscore')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const HiscoreLazyRoute = HiscoreLazyImport.update({
  id: '/hiscore',
  path: '/hiscore',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/hiscore.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/hiscore': {
      id: '/hiscore'
      path: '/hiscore'
      fullPath: '/hiscore'
      preLoaderRoute: typeof HiscoreLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/hiscore': typeof HiscoreLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/hiscore': typeof HiscoreLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/hiscore': typeof HiscoreLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hiscore'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hiscore'
  id: '__root__' | '/' | '/hiscore'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  HiscoreLazyRoute: typeof HiscoreLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  HiscoreLazyRoute: HiscoreLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hiscore"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/hiscore": {
      "filePath": "hiscore.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
